#!/bin/sh

branches=$*

json() {
	# Loop through branches
	echo "["
	branchFirst=0
	for data in $branches; do 
	
		# Check for initial comma
		if [ "$branchFirst" -eq "0" ]
		then
			branchFirst=1
		else 
			echo ","
		fi
		
		echo -n \"$data\"
	done
	echo ']'
}

filename="post-update_$RANDOM.json"
json > "$filename"
response=$(curl -H "Accept: application/json" -H "Content-Type:application/json" -X POST -d "@$filename" --silent --write-out "\n%{http_code}" http://indtfazilv/git-smart-http/post-update)
rm -f "$filename"

IFS=$'\n'
for line in $response; do
	status="$status$error"
	error="$line"$'\n'
done
status="${status%?}"
error="${error%?}"

if [ "$error" -ge "400" ]; then
	echo "$status"
	exit 1
fi